spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.168.1.102:20008/hxzz_db
    username: hxzz
    password: abc123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 'x'
      pool-name: prod
      password: abc123
      jdbc-url: jdbc:postgresql://10.168.1.102:20008/hxzz_db

  redis:
    host: localhost
    database: 0
    port: 6379
    password: abc123
  jwt:
    secret: mySecret
    expire: 3600
    authorization: access-token
  profiles: production
